- hosts: node01
  gather_facts: true
  vars:
    my_name: Gopinath
  tasks:  
    - name: Display name
      debug:
        msg: "{{ my_name }}"

    - name: Display hostname from the Ansible-nodes file
      debug:
        var: hostvars[inventory_hostname].hostname    
    
    - name: Display hostname
      debug:
        var: hostvars[inventory_hostname]

          