- hosts: node01
  gather_facts: true
  vars:
    my_name: Gopinath
  tasks:  
    - name: Display name
      debug:
        msg: "{{ my_name }}"

    - name: Display hostname
      debug:
        var: hostvars[inventory_hostname].hostname    
    
    - name: Display stdout_lines[0] variable
      debug:
        var: result.stdout_lines[0]  

          