- hosts: web
  gather_facts: true
  become: true
  vars:
    httpd_port: 8080
    user_name: Gopinath
    
  tasks:
  #   - template:
  #       src: exercise-jinja-template.j2
  #       dest: /home/ec2-user/facts
  #   - debug: var=play_hosts

    - name: Changing the port number   
      template:
        src: httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf


    # - name: stop tomcat server
    #   service:
    #     name: tomcat
    #     state: stopped
    #     enabled: no

    - name: start httpd
      service: name=httpd state=started enabled=yes    
