- hosts: node01
  gather_facts: true
  become: true
  tasks:
    - name: Create Dir
      shell: mkdir -p /home/ec2-user/testdirAnsibl3
    - name: copying file from controller to node
      copy:
      src: /inventory/ansible-nodes
      dest: /temp1/ansible-nodes
    - name: to display the content of ansible-nodes in temp1 location
      shell: cat /tmp/ansible-nodes
    - name: Install apache packages
      yum:
        name: httpd
        state: present
    - name: Install git packages
      yum:
        name: git
        state: present
    - name: Git command
      git:
        repo: "https://github.com/becloudready/prometheus_monitoring.git"
        dest: /tmp2 
        version: HEAD
    - name: Install nginx packages
      yum:
        name: nginx
        state: present
    - name: starting nginx server
    - service:
        name: nginx
        state: started
        enabled: "yes"
    - name: file state
      file:
        path: /home/ec2-user/usingAnsible
        state: directory
    - name: file copy ansible
      copy:
        src: README.md
        dest: dest=/tmp3
